name: app_environment
channels:
  - snowflake
dependencies:
  - ipywidgets
  - matplotlib=3.7.2
  - numpy=1.24.3
  - openpyxl
  - scikit-learn=1.2.2
  - seaborn
  - shap
  - snowflake-ml-python=1.4.0
  - xgboost=1.7.3